// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: janus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_BUY  Side = 0
	Side_SELL Side = 1
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	Side_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_janus_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_janus_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_LIMIT  OrderType = 0
	OrderType_MARKET OrderType = 1
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "LIMIT",
		1: "MARKET",
	}
	OrderType_value = map[string]int32{
		"LIMIT":  0,
		"MARKET": 1,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_janus_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_janus_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{1}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          Side                   `protobuf:"varint,3,opt,name=side,proto3,enum=janus.Side" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,4,opt,name=type,proto3,enum=janus.OrderType" json:"type,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint64                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Remaining     uint64                 `protobuf:"varint,7,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_janus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_BUY
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_LIMIT
}

func (x *Order) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetRemaining() uint64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint64                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MakerOrderId  uint64                 `protobuf:"varint,5,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId  uint64                 `protobuf:"varint,6,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_janus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{1}
}

func (x *Trade) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetMakerOrderId() uint64 {
	if x != nil {
		return x.MakerOrderId
	}
	return 0
}

func (x *Trade) GetTakerOrderId() uint64 {
	if x != nil {
		return x.TakerOrderId
	}
	return 0
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint64                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_janus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{2}
}

func (x *PriceLevel) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLevel) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          Side                   `protobuf:"varint,2,opt,name=side,proto3,enum=janus.Side" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,3,opt,name=type,proto3,enum=janus.OrderType" json:"type,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint64                 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_janus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubmitOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_BUY
}

func (x *SubmitOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_LIMIT
}

func (x *SubmitOrderRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SubmitOrderRequest) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SubmitOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_janus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *SubmitOrderResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_janus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_janus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// OrderCommand is one entry sent into OrderStream, tagged with a correlation_id the client picks
// so the matching OrderEvent can be routed back to the caller waiting on it.
type OrderCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint64                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*OrderCommand_Submit
	//	*OrderCommand_Cancel
	Command       isOrderCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCommand) Reset() {
	*x = OrderCommand{}
	mi := &file_janus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommand) ProtoMessage() {}

func (x *OrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommand.ProtoReflect.Descriptor instead.
func (*OrderCommand) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{7}
}

func (x *OrderCommand) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *OrderCommand) GetCommand() isOrderCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *OrderCommand) GetSubmit() *SubmitOrderRequest {
	if x != nil {
		if x, ok := x.Command.(*OrderCommand_Submit); ok {
			return x.Submit
		}
	}
	return nil
}

func (x *OrderCommand) GetCancel() *CancelOrderRequest {
	if x != nil {
		if x, ok := x.Command.(*OrderCommand_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isOrderCommand_Command interface {
	isOrderCommand_Command()
}

type OrderCommand_Submit struct {
	Submit *SubmitOrderRequest `protobuf:"bytes,2,opt,name=submit,proto3,oneof"`
}

type OrderCommand_Cancel struct {
	Cancel *CancelOrderRequest `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

func (*OrderCommand_Submit) isOrderCommand_Command() {}

func (*OrderCommand_Cancel) isOrderCommand_Command() {}

// OrderEvent is OrderStream's reply to one OrderCommand, carrying the same correlation_id back.
// Errors ride in-band (OrderError), not the stream's own gRPC status - one failed command can't tear down the stream others are still using.
type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint64                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*OrderEvent_SubmitResult
	//	*OrderEvent_CancelResult
	//	*OrderEvent_Error
	Event         isOrderEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_janus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{8}
}

func (x *OrderEvent) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *OrderEvent) GetEvent() isOrderEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *OrderEvent) GetSubmitResult() *SubmitOrderResponse {
	if x != nil {
		if x, ok := x.Event.(*OrderEvent_SubmitResult); ok {
			return x.SubmitResult
		}
	}
	return nil
}

func (x *OrderEvent) GetCancelResult() *CancelOrderResponse {
	if x != nil {
		if x, ok := x.Event.(*OrderEvent_CancelResult); ok {
			return x.CancelResult
		}
	}
	return nil
}

func (x *OrderEvent) GetError() *OrderError {
	if x != nil {
		if x, ok := x.Event.(*OrderEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOrderEvent_Event interface {
	isOrderEvent_Event()
}

type OrderEvent_SubmitResult struct {
	SubmitResult *SubmitOrderResponse `protobuf:"bytes,2,opt,name=submit_result,json=submitResult,proto3,oneof"`
}

type OrderEvent_CancelResult struct {
	CancelResult *CancelOrderResponse `protobuf:"bytes,3,opt,name=cancel_result,json=cancelResult,proto3,oneof"`
}

type OrderEvent_Error struct {
	Error *OrderError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*OrderEvent_SubmitResult) isOrderEvent_Event() {}

func (*OrderEvent_CancelResult) isOrderEvent_Event() {}

func (*OrderEvent_Error) isOrderEvent_Event() {}

type OrderError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // a google.golang.org/grpc/codes.Code value
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderError) Reset() {
	*x = OrderError{}
	mi := &file_janus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderError) ProtoMessage() {}

func (x *OrderError) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderError.ProtoReflect.Descriptor instead.
func (*OrderError) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{9}
}

func (x *OrderError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_janus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderBookRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type GetOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookResponse) Reset() {
	*x = GetOrderBookResponse{}
	mi := &file_janus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookResponse) ProtoMessage() {}

func (x *GetOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookResponse.ProtoReflect.Descriptor instead.
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderBookResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderBookResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetOrderBookResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

type SubscribeTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTradesRequest) Reset() {
	*x = SubscribeTradesRequest{}
	mi := &file_janus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTradesRequest) ProtoMessage() {}

func (x *SubscribeTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTradesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTradesRequest) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_janus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{13}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_janus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{14}
}

func (x *PingResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type MarketSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	HasTraded     bool                   `protobuf:"varint,2,opt,name=has_traded,json=hasTraded,proto3" json:"has_traded,omitempty"`
	LastPrice     int64                  `protobuf:"varint,3,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	OpenPrice     int64                  `protobuf:"varint,4,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	High          int64                  `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           int64                  `protobuf:"varint,6,opt,name=low,proto3" json:"low,omitempty"`
	Volume        uint64                 `protobuf:"varint,7,opt,name=volume,proto3" json:"volume,omitempty"`
	BestBid       *PriceLevel            `protobuf:"bytes,8,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	BestAsk       *PriceLevel            `protobuf:"bytes,9,opt,name=best_ask,json=bestAsk,proto3" json:"best_ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketSummary) Reset() {
	*x = MarketSummary{}
	mi := &file_janus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketSummary) ProtoMessage() {}

func (x *MarketSummary) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketSummary.ProtoReflect.Descriptor instead.
func (*MarketSummary) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{15}
}

func (x *MarketSummary) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MarketSummary) GetHasTraded() bool {
	if x != nil {
		return x.HasTraded
	}
	return false
}

func (x *MarketSummary) GetLastPrice() int64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *MarketSummary) GetOpenPrice() int64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *MarketSummary) GetHigh() int64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *MarketSummary) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *MarketSummary) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MarketSummary) GetBestBid() *PriceLevel {
	if x != nil {
		return x.BestBid
	}
	return nil
}

func (x *MarketSummary) GetBestAsk() *PriceLevel {
	if x != nil {
		return x.BestAsk
	}
	return nil
}

type ListSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsRequest) Reset() {
	*x = ListSymbolsRequest{}
	mi := &file_janus_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsRequest) ProtoMessage() {}

func (x *ListSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsRequest.ProtoReflect.Descriptor instead.
func (*ListSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{16}
}

type ListSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*MarketSummary       `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsResponse) Reset() {
	*x = ListSymbolsResponse{}
	mi := &file_janus_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsResponse) ProtoMessage() {}

func (x *ListSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsResponse.ProtoReflect.Descriptor instead.
func (*ListSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{17}
}

func (x *ListSymbolsResponse) GetMarkets() []*MarketSummary {
	if x != nil {
		return x.Markets
	}
	return nil
}

type GetTradeHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeHistoryRequest) Reset() {
	*x = GetTradeHistoryRequest{}
	mi := &file_janus_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeHistoryRequest) ProtoMessage() {}

func (x *GetTradeHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTradeHistoryRequest) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{18}
}

func (x *GetTradeHistoryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetTradeHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeHistoryResponse) Reset() {
	*x = GetTradeHistoryResponse{}
	mi := &file_janus_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeHistoryResponse) ProtoMessage() {}

func (x *GetTradeHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTradeHistoryResponse) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{19}
}

func (x *GetTradeHistoryResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTradeHistoryResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type RegisterMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMarketRequest) Reset() {
	*x = RegisterMarketRequest{}
	mi := &file_janus_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMarketRequest) ProtoMessage() {}

func (x *RegisterMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMarketRequest.ProtoReflect.Descriptor instead.
func (*RegisterMarketRequest) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterMarketRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RegisterMarketRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *MarketSummary         `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMarketResponse) Reset() {
	*x = RegisterMarketResponse{}
	mi := &file_janus_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMarketResponse) ProtoMessage() {}

func (x *RegisterMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_janus_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMarketResponse.ProtoReflect.Descriptor instead.
func (*RegisterMarketResponse) Descriptor() ([]byte, []int) {
	return file_janus_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterMarketResponse) GetMarket() *MarketSummary {
	if x != nil {
		return x.Market
	}
	return nil
}

var File_janus_proto protoreflect.FileDescriptor

const file_janus_proto_rawDesc = "" +
	"\n" +
	"\vjanus.proto\x12\x05janus\"\xc6\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1f\n" +
	"\x04side\x18\x03 \x01(\x0e2\v.janus.SideR\x04side\x12$\n" +
	"\x04type\x18\x04 \x01(\x0e2\x10.janus.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x04R\bquantity\x12\x1c\n" +
	"\tremaining\x18\a \x01(\x04R\tremaining\"\xad\x01\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x04R\bquantity\x12$\n" +
	"\x0emaker_order_id\x18\x05 \x01(\x04R\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\x06 \x01(\x04R\ftakerOrderId\">\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x04R\bquantity\"\xa5\x01\n" +
	"\x12SubmitOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\x04side\x18\x02 \x01(\x0e2\v.janus.SideR\x04side\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.janus.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x04R\bquantity\"_\n" +
	"\x13SubmitOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.janus.OrderR\x05order\x12$\n" +
	"\x06trades\x18\x02 \x03(\v2\f.janus.TradeR\x06trades\"G\n" +
	"\x12CancelOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"9\n" +
	"\x13CancelOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.janus.OrderR\x05order\"\xaa\x01\n" +
	"\fOrderCommand\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\x04R\rcorrelationId\x123\n" +
	"\x06submit\x18\x02 \x01(\v2\x19.janus.SubmitOrderRequestH\x00R\x06submit\x123\n" +
	"\x06cancel\x18\x03 \x01(\v2\x19.janus.CancelOrderRequestH\x00R\x06cancelB\t\n" +
	"\acommand\"\xed\x01\n" +
	"\n" +
	"OrderEvent\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\x04R\rcorrelationId\x12A\n" +
	"\rsubmit_result\x18\x02 \x01(\v2\x1a.janus.SubmitOrderResponseH\x00R\fsubmitResult\x12A\n" +
	"\rcancel_result\x18\x03 \x01(\v2\x1a.janus.CancelOrderResponseH\x00R\fcancelResult\x12)\n" +
	"\x05error\x18\x04 \x01(\v2\x11.janus.OrderErrorH\x00R\x05errorB\a\n" +
	"\x05event\":\n" +
	"\n" +
	"OrderError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x13GetOrderBookRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"|\n" +
	"\x14GetOrderBookResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12%\n" +
	"\x04bids\x18\x02 \x03(\v2\x11.janus.PriceLevelR\x04bids\x12%\n" +
	"\x04asks\x18\x03 \x03(\v2\x11.janus.PriceLevelR\x04asks\"0\n" +
	"\x16SubscribeTradesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\r\n" +
	"\vPingRequest\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\"\xc0\x02\n" +
	"\rMarketSummary\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"has_traded\x18\x02 \x01(\bR\thasTraded\x12\x1d\n" +
	"\n" +
	"last_price\x18\x03 \x01(\x03R\tlastPrice\x12\x1d\n" +
	"\n" +
	"open_price\x18\x04 \x01(\x03R\topenPrice\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x03R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x03R\x03low\x12\x16\n" +
	"\x06volume\x18\a \x01(\x04R\x06volume\x12,\n" +
	"\bbest_bid\x18\b \x01(\v2\x11.janus.PriceLevelR\abestBid\x12,\n" +
	"\bbest_ask\x18\t \x01(\v2\x11.janus.PriceLevelR\abestAsk\"\x14\n" +
	"\x12ListSymbolsRequest\"E\n" +
	"\x13ListSymbolsResponse\x12.\n" +
	"\amarkets\x18\x01 \x03(\v2\x14.janus.MarketSummaryR\amarkets\"0\n" +
	"\x16GetTradeHistoryRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"W\n" +
	"\x17GetTradeHistoryResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12$\n" +
	"\x06trades\x18\x02 \x03(\v2\f.janus.TradeR\x06trades\"Q\n" +
	"\x15RegisterMarketRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"F\n" +
	"\x16RegisterMarketResponse\x12,\n" +
	"\x06market\x18\x01 \x01(\v2\x14.janus.MarketSummaryR\x06market*\x19\n" +
	"\x04Side\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x01*\"\n" +
	"\tOrderType\x12\t\n" +
	"\x05LIMIT\x10\x00\x12\n" +
	"\n" +
	"\x06MARKET\x10\x012\xe8\x03\n" +
	"\bExchange\x129\n" +
	"\vOrderStream\x12\x13.janus.OrderCommand\x1a\x11.janus.OrderEvent(\x010\x01\x12G\n" +
	"\fGetOrderBook\x12\x1a.janus.GetOrderBookRequest\x1a\x1b.janus.GetOrderBookResponse\x12@\n" +
	"\x0fSubscribeTrades\x12\x1d.janus.SubscribeTradesRequest\x1a\f.janus.Trade0\x01\x12/\n" +
	"\x04Ping\x12\x12.janus.PingRequest\x1a\x13.janus.PingResponse\x12D\n" +
	"\vListSymbols\x12\x19.janus.ListSymbolsRequest\x1a\x1a.janus.ListSymbolsResponse\x12P\n" +
	"\x0fGetTradeHistory\x12\x1d.janus.GetTradeHistoryRequest\x1a\x1e.janus.GetTradeHistoryResponse\x12M\n" +
	"\x0eRegisterMarket\x12\x1c.janus.RegisterMarketRequest\x1a\x1d.janus.RegisterMarketResponseB7Z5github.com/guilhermemcandido/janus/internal/api/protob\x06proto3"

var (
	file_janus_proto_rawDescOnce sync.Once
	file_janus_proto_rawDescData []byte
)

func file_janus_proto_rawDescGZIP() []byte {
	file_janus_proto_rawDescOnce.Do(func() {
		file_janus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_janus_proto_rawDesc), len(file_janus_proto_rawDesc)))
	})
	return file_janus_proto_rawDescData
}

var file_janus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_janus_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_janus_proto_goTypes = []any{
	(Side)(0),                       // 0: janus.Side
	(OrderType)(0),                  // 1: janus.OrderType
	(*Order)(nil),                   // 2: janus.Order
	(*Trade)(nil),                   // 3: janus.Trade
	(*PriceLevel)(nil),              // 4: janus.PriceLevel
	(*SubmitOrderRequest)(nil),      // 5: janus.SubmitOrderRequest
	(*SubmitOrderResponse)(nil),     // 6: janus.SubmitOrderResponse
	(*CancelOrderRequest)(nil),      // 7: janus.CancelOrderRequest
	(*CancelOrderResponse)(nil),     // 8: janus.CancelOrderResponse
	(*OrderCommand)(nil),            // 9: janus.OrderCommand
	(*OrderEvent)(nil),              // 10: janus.OrderEvent
	(*OrderError)(nil),              // 11: janus.OrderError
	(*GetOrderBookRequest)(nil),     // 12: janus.GetOrderBookRequest
	(*GetOrderBookResponse)(nil),    // 13: janus.GetOrderBookResponse
	(*SubscribeTradesRequest)(nil),  // 14: janus.SubscribeTradesRequest
	(*PingRequest)(nil),             // 15: janus.PingRequest
	(*PingResponse)(nil),            // 16: janus.PingResponse
	(*MarketSummary)(nil),           // 17: janus.MarketSummary
	(*ListSymbolsRequest)(nil),      // 18: janus.ListSymbolsRequest
	(*ListSymbolsResponse)(nil),     // 19: janus.ListSymbolsResponse
	(*GetTradeHistoryRequest)(nil),  // 20: janus.GetTradeHistoryRequest
	(*GetTradeHistoryResponse)(nil), // 21: janus.GetTradeHistoryResponse
	(*RegisterMarketRequest)(nil),   // 22: janus.RegisterMarketRequest
	(*RegisterMarketResponse)(nil),  // 23: janus.RegisterMarketResponse
}
var file_janus_proto_depIdxs = []int32{
	0,  // 0: janus.Order.side:type_name -> janus.Side
	1,  // 1: janus.Order.type:type_name -> janus.OrderType
	0,  // 2: janus.SubmitOrderRequest.side:type_name -> janus.Side
	1,  // 3: janus.SubmitOrderRequest.type:type_name -> janus.OrderType
	2,  // 4: janus.SubmitOrderResponse.order:type_name -> janus.Order
	3,  // 5: janus.SubmitOrderResponse.trades:type_name -> janus.Trade
	2,  // 6: janus.CancelOrderResponse.order:type_name -> janus.Order
	5,  // 7: janus.OrderCommand.submit:type_name -> janus.SubmitOrderRequest
	7,  // 8: janus.OrderCommand.cancel:type_name -> janus.CancelOrderRequest
	6,  // 9: janus.OrderEvent.submit_result:type_name -> janus.SubmitOrderResponse
	8,  // 10: janus.OrderEvent.cancel_result:type_name -> janus.CancelOrderResponse
	11, // 11: janus.OrderEvent.error:type_name -> janus.OrderError
	4,  // 12: janus.GetOrderBookResponse.bids:type_name -> janus.PriceLevel
	4,  // 13: janus.GetOrderBookResponse.asks:type_name -> janus.PriceLevel
	4,  // 14: janus.MarketSummary.best_bid:type_name -> janus.PriceLevel
	4,  // 15: janus.MarketSummary.best_ask:type_name -> janus.PriceLevel
	17, // 16: janus.ListSymbolsResponse.markets:type_name -> janus.MarketSummary
	3,  // 17: janus.GetTradeHistoryResponse.trades:type_name -> janus.Trade
	17, // 18: janus.RegisterMarketResponse.market:type_name -> janus.MarketSummary
	9,  // 19: janus.Exchange.OrderStream:input_type -> janus.OrderCommand
	12, // 20: janus.Exchange.GetOrderBook:input_type -> janus.GetOrderBookRequest
	14, // 21: janus.Exchange.SubscribeTrades:input_type -> janus.SubscribeTradesRequest
	15, // 22: janus.Exchange.Ping:input_type -> janus.PingRequest
	18, // 23: janus.Exchange.ListSymbols:input_type -> janus.ListSymbolsRequest
	20, // 24: janus.Exchange.GetTradeHistory:input_type -> janus.GetTradeHistoryRequest
	22, // 25: janus.Exchange.RegisterMarket:input_type -> janus.RegisterMarketRequest
	10, // 26: janus.Exchange.OrderStream:output_type -> janus.OrderEvent
	13, // 27: janus.Exchange.GetOrderBook:output_type -> janus.GetOrderBookResponse
	3,  // 28: janus.Exchange.SubscribeTrades:output_type -> janus.Trade
	16, // 29: janus.Exchange.Ping:output_type -> janus.PingResponse
	19, // 30: janus.Exchange.ListSymbols:output_type -> janus.ListSymbolsResponse
	21, // 31: janus.Exchange.GetTradeHistory:output_type -> janus.GetTradeHistoryResponse
	23, // 32: janus.Exchange.RegisterMarket:output_type -> janus.RegisterMarketResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_janus_proto_init() }
func file_janus_proto_init() {
	if File_janus_proto != nil {
		return
	}
	file_janus_proto_msgTypes[7].OneofWrappers = []any{
		(*OrderCommand_Submit)(nil),
		(*OrderCommand_Cancel)(nil),
	}
	file_janus_proto_msgTypes[8].OneofWrappers = []any{
		(*OrderEvent_SubmitResult)(nil),
		(*OrderEvent_CancelResult)(nil),
		(*OrderEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_janus_proto_rawDesc), len(file_janus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_janus_proto_goTypes,
		DependencyIndexes: file_janus_proto_depIdxs,
		EnumInfos:         file_janus_proto_enumTypes,
		MessageInfos:      file_janus_proto_msgTypes,
	}.Build()
	File_janus_proto = out.File
	file_janus_proto_goTypes = nil
	file_janus_proto_depIdxs = nil
}
